### ISSUE TITLE
Set up MySQL db with User, Role, Interest, Tutorial

### ISSUE THREAD

**Issue by kbuffardi** [kbuffardi/CodeWitUs#3]
We need a relational MySQL database with the following objects:

# User

* id (unique, auto-increment, primary key)
* email address (unique)
* [any additional info required for oauth]
* date of registration (Date)
* major (string)
* age (integer)
* gender (string)
* role [has one]
* interest [has many]

# Role

*For now, each user will have one (and only one) role, but we want a dedicated object for future extensibility. Initial values will be:*

* id (unique, auto-increment, primary key)
* learner
* creator
* admin

# Interest
*interests will be topics like personal interests or hobbies. They will be associated (many-to-many) with other objects, including User, but also other objects*

* id (unique, auto-increment, primary key)
* name (unique)

We need to configure the app to default to MySQL (instead of SQLite) and build the initial tables. The development environment should also support it.

**Comment by kbuffardi** [comment]
For **Role** we should use the `cancancan` gem. It's mature, feature-rich, and well-supported.

**Comment by kbuffardi** [comment]
This is a start to #2 but more attributes will be added to this in the future.

**Comment by kbuffardi** [comment]
I just updated the description to finalize the initial Schema with additional demographic information @subhed

**Comment by kbuffardi** [comment]
closes #2

**Comment by subhed** [comment]
Thank You! @kbuffardi

**Comment by kbuffardi** [comment]
# Tutorial

* id (unique, hashed, primary key)
* name (string)
* video (youtube embed url)
* exercise (codeworkout exercise url)
* creator [has one User]
* date created (date)
* interests [has many]
* concepts [has one or more]


# Concept
*Concepts will be programming concepts such as decisions, functions, iteration, etc.*

* id (unique, auto-increment, primary key)
* name

**Comment by kbuffardi** [comment]
Reopened. The tutorial and concept models/schema are not finished.

In addition, we need to *seed* the database with the following concepts (names):

* functions
* parameters
* decisions
* iteration
* operations
* variables
* boolean expressions
* arrays
* vectors
* matrices
* recursion
* number systems
* structs
* pointers
* sorting
* input/output
* file streams
* classes
* randomization

**Comment by kbuffardi** [comment]
Resolved with pull request #26
