### ISSUE TITLE
Validate and enforce password rules

### ISSUE THREAD

**Issue by kbuffardi** [kbuffardi/CodeWitUs#6]
These rules will only apply to accounts made on codewit.us and not those authenticated through external OAuth.

- [x] passwords should be at least 12 characters
- [x] no restrictions/requirements on types of characters/case

Within the site, passwords should:

- [x] be [hashed and salted](https://auth0.com/blog/adding-salt-to-hashing-a-better-way-to-store-passwords/)

**Comment by subhed** [comment]
Completed.
